# Gradle 記憶體設定
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Fabric 核心版本
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.8-SNAPSHOT

# 模組屬性
mod_version=1.0.0
maven_group=com.example
archives_base_name=tntrun

# Fabric API
fabric_api_version=0.161.0+26.3
